### ISSUE TITLE
Error in running segmental_duplication_detector.py

### ISSUE THREAD

**Issue by soumyarao86** [nlapalu/SDDetector#1]
Hi Nicolas,

I have been trying to run SDdetector but end up with the following error.

$/home/softwares/SDDetector/bin/segmental_duplication_detector.py blast_masked1.tab tab sdd_0.9_3000_5000.gff3 :memory: -g 3000 -l 5000 -a

`Traceback (most recent call last):
  File "/home/softwares/SDDetector/bin/segmental_duplication_detector.py", line 257, in <module>
    logging.getLogger().setLevel(logLevel)
NameError: name 'logLevel' is not defined`

Please help me fix it.

Thanks and regards,
Soumya,
CDFD,
Hyderabad,
India

**Comment by nlapalu** [comment]
Hi Soumya,

Please excuse my late response,, I was out of the office for several days. It's a simple error, I will fix it asap. To avoid this error, set a log level on the command line with -v 1 (None) or -v 2 (INFO) or -v 3 (DEBUG). Let me know if you encounter other issues.

regards,

nico

**Comment by soumyarao86** [comment]
Hi Nicolas,

Thanks a lot for the tip.
It worked just fine!

Regards,
Soumya
