### ISSUE TITLE
Run time

### ISSUE THREAD

**Issue by yeban** [nlapalu/SDDetector#2]
Hi,

I ran SDDetector using a 13 GB BLAST XML input. It has run for 15 days now but not finished. Is this normal? Please could you advice how I might be able to speed it up?

**Comment by nlapalu** [comment]
Hi

Sorry, I'm out of office for 3 weeks, it will be difficult for me to help you. What is your genome, species ? Did you have soft masked your genome ? If the TE content is  not null it is necessary to avoid false positives and unecessary time computation.
Nico

----------------------------
Nicolas Lapalu
Bioinformatics

INRA - UMR1290 BIOGER
INRA-AgroParisTech
Avenue Lucien Bretignieres
78850 Thiverval-Grignon

email: nicolas.lapalu@inra.fr
tel: +33130815409
----------------------------

________________________________________
De : Anurag Priyam [notifications@github.com]
Envoyé : lundi 30 juillet 2018 13:31
À : nlapalu/SDDetector
Cc : Subscribed
Objet : [nlapalu/SDDetector] Run time (#2)

Hi,

I ran SDDetector using a 13 GB BLAST XML input. It has run for 15 days now but not finished. Is this normal? Please could you advice how I might be able to speed it up?

**Comment by yeban** [comment]
Thanks for letting me know. It's a ~400 Mb insect genome. Yes, I soft-masked the assembly. I used RepeatMasker (with a custom repeat library inferred from Illumina reads). Though, I took a slightly different approach (than in the README) for creating masked BLAST database:

```
    # Get masking information from lowercase bases in the FASTA file. Output
    # (*.asnb) is passed to makeblastdb in the next step.
    convert2blastmask -in pilon_masked_renamed_A_ref.fa -parse_seqids  \
    -masking_algorithm repeat -masking_options "repeatmasker, default" \
    -outfmt maskinfo_asn1_bin -out pilon_masked_renamed_A_ref.asnb

    # Create BLASTDB with masking information.
    makeblastdb -dbtype nucl -in pilon_masked_renamed_A_ref.fa \
    -out pilon_masked_renamed_A_ref.fa -parse_seqids \
    -mask_data pilon_masked_renamed_A_ref.asnb

    # Get database info and note the algorithm id. This is used with
    # -db_soft_mask option in the next step
    blastdbcmd -db pilon_masked_renamed_A_ref.fa -info

    # Now run BLAST.
    blastn -num_threads 20 -task megablast -db pilon_masked_renamed_A_ref.fa \
    -query pilon_masked_renamed_A_ref.fa -out blast.xml -outfmt 5 \
    -db_soft_mask 40
```

**Comment by nlapalu** [comment]
I never tried with a such genome size. I will have to change the simple algorithm of the tool. You can try to use hard masking instead of soft masking, that will avoid alignment extensions in TE.

**Comment by nlapalu** [comment]
Hi Yeban,

Sorry for this delayed answer. Did you try an hard masking ? If you want, I can try with your data ?

**Comment by yeban** [comment]
Hey, I understand :). I didn't try hard masking. I tried raising evalue 1e-50. This resulted in roughly 8-9 Gb of BLAST output. I let SDDetector process it for 5-6 days before terminating the process.

Roughly 33% of my genome is masked. I guess in the best case scenario hard masking can reduce BLAST output by 1/3rd, so roughly 5-6 Gb. Do you think that will be feasible for SDDetector? How big are the BLAST files that have you been working with?

I guess my plan finally is to try TBLASTX. That should reduce the number of alignments dramatically. Just that I have been held up with other things. Do you think SDDetector could be easily adapted to used TBLASTX output?

I would be very interested to collaborate, but I will have to check with my supervisor before I can share any data.

**Comment by nlapalu** [comment]
Hi,

I have only tested on files smaller than 1GB. Maybe try hard masking and a minimum size for match length (SDDetector option), to avoid too small matches when the program try to join matches.
I don't know the difference in a blastn vs tblastx output xml, but I think it is very similar. I have to check ! It will be quite easy to modify the parser to deal with it. I can try if you want.

**Comment by yeban** [comment]
Thanks @nlapalu. Knowing that you have tested on smaller than 1GB BLAST output and learning about the minimum match length (`-t`) option adds much-needed perspective.
