### ISSUE TITLE
Problem at installation

### ISSUE THREAD

**Issue by pabloangulo7** [nlapalu/SDDetector#7]
Hello,

I would like to use SDDetector to detect duplicated genes in a reference genome fasta file. When I try to install the program I obtain this error: 

![SDDetector](https://user-images.githubusercontent.com/70705390/217301353-cbc80eb2-3426-4488-9fcc-b8beab86d7a9.png)

Could you help me to resolve it? Is there available any docker version in order to avoid this kind of errors?

Best and thanks in advance

Pablo

**Comment by nlapalu** [comment]
Hi Pablo,

I removed the tab in a quick and dirty fix via the github interface. You can try to reinstall the code and run the tests. Do you use Python  2.7.X ? I didn't get any warnings or errors with my version...strange.

**Comment by pabloangulo7** [comment]
Hi,

Thank you. Sorry, it was my mistake since I was using Python 3.X. With Pyhton 2.7.X works without problems
