### ISSUE TITLE
confused about creating blast database

### ISSUE THREAD

**Issue by Shuixin-Li** [nlapalu/SDDetector#8]
Hi, thank you for providing such amazing work. I tried to follow the best practice but I encounter such problem

```
$ makeblastdb -dbtype nucl -in genome_masked.fasta -out genome_masked -parse_seqids -mask_data genome_masked.asnb


Building a new DB, current time: 03/12/2024 13:53:39
New DB name:  *****/genome_masked
New DB title:  genome_masked.fasta
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Mask file: genome_masked.asnb
Adding sequences from FASTA; added 3144 sequences in 38.5053 seconds.


Error: [makeblastdb] No sequences matched any of the masks provided.
Please ensure that the -parse_seqids option is used in the
filtering program as well as makeblastdb.
```

I did not get it especially `Please ensure that the -parse_seqids option is used in the
filtering program as well as makeblastdb.` . I follow every steps and did not change anything. (I don't even change the file name...). 

And when I check the information of the database, it does not give me the **Algorithm ID** as you shows in the readme file. 
```
$ blastdbcmd -db genome_masked -info
Database: genome_masked.fasta
	3,144 sequences; 2,723,219,641 total bases

Date: Mar 12, 2024  1:53 PM	Longest sequence: 88,675,666 bases

BLASTDB Version: 5

Volumes:
	*****/genome_masked
```

without the Algorithm ID, I cannot get to the next step `blastn -num_threads 2 -task megablast -db genome_masked -query genome.fasta -out blast.xml -outfmt 5 -db_soft_mask 100` 

```
BLAST options error: Masking algorithm ID 100 is not supported in nucleotide 'genome_masked' BLAST database
```

Thank you very much!

**Comment by nlapalu** [comment]
Hi,

How are your accession lines (>) defined ? Do you have a complex pattern like: `> gnl|ACC|desc mydesc, my organism`. If so, 
try reducing it to something simpler like `>ACC`.

Nico

**Comment by Shuixin-Li** [comment]
Really thank you for your reply. I am new to this field so I am not sure whether you mean the accession line in the fasta file. if so ,I checked the accession lines, it looked like `>NT_173914.1` . 

Is `>NT_173914.1` simple enough? Should I change this into more simple version like `>NT`? 

If so, Should I use different accession line, such as NT1, NT2 for different sequences?

Thank you again for your kindly reply! ;)

**Comment by nlapalu** [comment]
I have already had this bug. The problem is with the "-". I don't know why.
So change the name of your sequence with a cmd like this one:
`sed 's/\.1//' genome_masked.fasta | sed 's/_//' | fold -w 60 > genome_masked.clean.fasta`
Nico

**Comment by Shuixin-Li** [comment]
Hi Nico, I used your magic line and then problem sloved! Thank you very much!
